spring: 
  datasource:
    username: xray_facility
    password: xray_facility
    url: jdbc:mysql://localhost:3306/xray_facility
    
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true 
   
    
  sql:
    init:
      mode: always 